-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Dull Hatchet"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 4, PhysicalMax = 10, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { },
}
itemBases["Hook Axe"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicit = "Grants 1 Rage on Hit",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 5, PhysicalMax = 14, CritChanceBase = 5, AttackRateBase = 1.45, Range = 11, },
	req = { str = 9, },
}
itemBases["Bearded Axe"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, ezomyte_basetype = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 8, PhysicalMax = 21, CritChanceBase = 5, AttackRateBase = 1.45, Range = 11, },
	req = { level = 10, str = 17, dex = 9, },
}
itemBases["Extended Cleaver"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicit = "Has no Accuracy Penalty from Range",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 8, PhysicalMax = 25, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 16, str = 25, dex = 12, },
}
itemBases["Bandit Hatchet"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 13, PhysicalMax = 31, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 20, str = 30, dex = 14, },
}
itemBases["Crescent Axe"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, maraketh_basetype = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 18, PhysicalMax = 37, CritChanceBase = 6.5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 26, str = 38, dex = 17, },
}
itemBases["Carving Hatchet"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, vaal_basetype = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 19, PhysicalMax = 44, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 33, str = 47, dex = 20, },
}
itemBases["Sacrificial Axe"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, vaal_basetype = true, weapon = true, },
	implicit = "Gain (28-35) Mana per enemy killed",
	implicitModTypes = { { "resource", "mana" }, },
	weapon = { PhysicalMin = 20, PhysicalMax = 42, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 37, str = 52, dex = 22, },
}
itemBases["Boarding Hatchet"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 24, PhysicalMax = 55, CritChanceBase = 5, AttackRateBase = 1.55, Range = 11, },
	req = { level = 45, str = 63, dex = 26, },
}
itemBases["Fury Cleaver"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicit = "10% increased Damage taken",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 30, PhysicalMax = 62, CritChanceBase = 5, AttackRateBase = 1.55, Range = 11, },
	req = { level = 48, str = 67, dex = 27, },
}
itemBases["Battle Axe"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 28, PhysicalMax = 65, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 52, str = 72, dex = 29, },
}
itemBases["Profane Cleaver"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 26, PhysicalMax = 69, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 54, str = 75, dex = 30, },
}
itemBases["Dread Hatchet"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 34, PhysicalMax = 79, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 65, str = 89, dex = 36, },
}
itemBases["[DNT] Callous Hatchet"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 35, PhysicalMax = 81, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 67, str = 89, dex = 36, },
}
itemBases["[DNT] Catcher Axe"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 37, PhysicalMax = 86, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 72, str = 89, dex = 36, },
}
itemBases["[DNT] Aged Axe"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 39, PhysicalMax = 91, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 77, str = 89, dex = 36, },
}
itemBases["[DNT] Towering Axe"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 39, PhysicalMax = 91, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 78, str = 89, dex = 36, },
}
itemBases["[DNT] Vagabond Axe"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 39, PhysicalMax = 91, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 79, str = 89, dex = 36, },
}
itemBases["[DNT] Moonlight Axe"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 39, PhysicalMax = 91, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 77, str = 89, dex = 36, },
}
itemBases["[DNT] Hacking Hatchet"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 38, PhysicalMax = 89, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 75, str = 89, dex = 36, },
}
itemBases["[DNT] Ritualistic Axe"] = {
	type = "One Handed Axe",
	quality = 20,
	socketLimit = 3,
	tags = { axe = true, default = true, one_hand_weapon = true, onehand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 39, PhysicalMax = 91, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 78, str = 89, dex = 36, },
}

itemBases["Splitting Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, ezomyte_basetype = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 8, PhysicalMax = 20, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { },
}
itemBases["Light Halberd"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, ezomyte_basetype = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 10, PhysicalMax = 25, CritChanceBase = 5, AttackRateBase = 1.25, Range = 13, },
	req = { str = 9, },
}
itemBases["Executioner Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, ezomyte_basetype = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "Culling Strike",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 10, PhysicalMax = 41, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 10, str = 17, dex = 9, },
}
itemBases["Arched Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, maraketh_basetype = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 17, PhysicalMax = 59, CritChanceBase = 5, AttackRateBase = 1.15, Range = 13, },
	req = { level = 16, str = 25, dex = 12, },
}
itemBases["Elegant Glaive"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, maraketh_basetype = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 19, PhysicalMax = 64, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 20, str = 30, dex = 14, },
}
itemBases["Savage Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, maraketh_basetype = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "Gain (34-43) Life per enemy killed",
	implicitModTypes = { { "resource", "life" }, },
	weapon = { PhysicalMin = 23, PhysicalMax = 70, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 27, str = 39, dex = 17, },
}
itemBases["Rending Halberd"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, vaal_basetype = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 27, PhysicalMax = 91, CritChanceBase = 6.5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 33, str = 47, dex = 20, },
}
itemBases["Jagged Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, vaal_basetype = true, weapon = true, },
	implicit = "(15-25)% chance to cause Bleeding on Hit",
	implicitModTypes = { { "bleed", "physical", "attack", "ailment" }, },
	weapon = { PhysicalMin = 43, PhysicalMax = 99, CritChanceBase = 5, AttackRateBase = 1.15, Range = 13, },
	req = { level = 40, str = 56, dex = 23, },
}
itemBases["Reaver Glaive"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 43, PhysicalMax = 113, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 45, str = 63, dex = 26, },
}
itemBases["Ember Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { FireMin = 58, FireMax = 154, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 50, str = 70, dex = 28, },
}
itemBases["Ceremonial Halberd"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicit = "Cannot use Projectile Attacks",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 53, PhysicalMax = 123, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 52, str = 72, dex = 29, },
}
itemBases["Monument Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 48, PhysicalMax = 143, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 57, str = 79, dex = 32, },
}
itemBases["Vile Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 59, PhysicalMax = 155, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 65, str = 89, dex = 36, },
}
itemBases["[DNT] Dividing Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 60, PhysicalMax = 159, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 67, str = 89, dex = 36, },
}
itemBases["[DNT] Feathersteel Halberd"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 64, PhysicalMax = 170, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 72, str = 89, dex = 36, },
}
itemBases["[DNT] Grimhold Axe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 68, PhysicalMax = 180, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 77, str = 89, dex = 36, },
}
itemBases["[DNT] Notched Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 68, PhysicalMax = 180, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 78, str = 89, dex = 36, },
}
itemBases["[DNT] Intricate Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 68, PhysicalMax = 180, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 79, str = 89, dex = 36, },
}
itemBases["[DNT] Violent Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 68, PhysicalMax = 180, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 77, str = 89, dex = 36, },
}
itemBases["[DNT] Severing Halberd"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 67, PhysicalMax = 176, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 75, str = 89, dex = 36, },
}
itemBases["[DNT] Clawed Greataxe"] = {
	type = "Two Handed Axe",
	quality = 20,
	socketLimit = 4,
	tags = { axe = true, default = true, two_hand_weapon = true, twohand = true, weapon = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 68, PhysicalMax = 180, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { level = 78, str = 89, dex = 36, },
}
