-- test/unit/test_modtools.lua
require("test_helpers")

-- Stub ModFlag and KeywordFlag
_G.ModFlag = { Attack = 1, Spell = 2, Hit = 4, Dot = 8, Cast = 16 }
_G.KeywordFlag = { Fire = 1, Cold = 2, Lightning = 4, Physical = 8 }

-- Load ModTools
dofile("PathOfBuilding.app/Contents/Resources/src/Modules/ModTools.lua")

describe("modLib.createMod", function()
    it("creates a basic mod", function()
        local mod = modLib.createMod("Life", "BASE", 50)
        assert.are.equal("Life", mod.name)
        assert.are.equal("BASE", mod.type)
        assert.are.equal(50, mod.value)
        assert.are.equal(0, mod.flags)
        assert.are.equal(0, mod.keywordFlags)
        assert.is_nil(mod.source)
    end)

    it("creates a mod with source string", function()
        local mod = modLib.createMod("Life", "BASE", 50, "Tree:Node")
        assert.are.equal("Tree:Node", mod.source)
    end)

    it("creates a mod with source, flags, keywordFlags", function()
        local mod = modLib.createMod("Damage", "INC", 20, "Item:Ring", 3, 5)
        assert.are.equal("Item:Ring", mod.source)
        assert.are.equal(3, mod.flags)
        assert.are.equal(5, mod.keywordFlags)
    end)

    it("handles tags after source/flags/keywordFlags", function()
        local tag = { type = "Condition", var = "Leeching" }
        local mod = modLib.createMod("Damage", "INC", 10, "Item:Belt", 0, 0, tag)
        assert.are.equal(tag, mod[1])
    end)

    it("produces C-compatible sequential tag structure", function()
        local tag1 = { type = "Condition", var = "A" }
        local tag2 = { type = "Condition", var = "B" }
        local mod = modLib.createMod("X", "BASE", 1, "src", 0, 0, tag1, tag2)
        assert.is_not_nil(mod[1])
        assert.is_not_nil(mod[2])
    end)
end)

describe("modLib.parseTags", function()
    it("returns empty table for nil input", function()
        assert.are.same({}, modLib.parseTags(nil))
    end)
    it("returns empty table for dash input", function()
        assert.are.same({}, modLib.parseTags("-"))
    end)
    it("parses a single tag with key=value", function()
        local result = modLib.parseTags("type=Condition")
        assert.are.equal(1, #result)
        assert.are.equal("Condition", result[1].type)
    end)
    it("parses slash-separated tag parameters", function()
        local result = modLib.parseTags("type=Condition/var=Leeching")
        assert.are.equal("Leeching", result[1].var)
    end)
    it("converts threshold value to number", function()
        local result = modLib.parseTags("type=StatThreshold/threshold=50")
        assert.are.equal(50, result[1].threshold)
        assert.are.equal("number", type(result[1].threshold))
    end)
    it("converts true string to boolean", function()
        local result = modLib.parseTags("type=Condition/neg=true")
        assert.are.equal(true, result[1].neg)
    end)
    it("handles invalid tag format gracefully", function()
        assert.has_no.errors(function()
            modLib.parseTags("badtag")
        end)
    end)
end)

describe("modLib.parseFormattedSourceMod", function()
    it("parses a complete formatted mod string", function()
        local line = "10|Tree:Node|Life|BASE|Attack|Fire|type=Condition/var=Test"
        local mod = modLib.parseFormattedSourceMod(line)
        assert.is_not_nil(mod)
        assert.are.equal(10, mod.value)
        assert.are.equal("Tree:Node", mod.source)
        assert.are.equal("Life", mod.name)
        assert.are.equal("BASE", mod.type)
    end)
    it("returns nil for incomplete string", function()
        assert.is_nil(modLib.parseFormattedSourceMod("10|Source"))
    end)
    it("returns nil for empty string", function()
        assert.is_nil(modLib.parseFormattedSourceMod(""))
    end)
end)

describe("modLib.compareModParams", function()
    it("returns true for identical mod params (value ignored)", function()
        local modA = modLib.createMod("Life", "BASE", 50, "Src", 1, 2)
        local modB = modLib.createMod("Life", "BASE", 100, "Src", 1, 2)
        assert.is_true(modLib.compareModParams(modA, modB))
    end)
    it("returns false when names differ", function()
        local modA = modLib.createMod("Life", "BASE", 50)
        local modB = modLib.createMod("Mana", "BASE", 50)
        assert.is_false(modLib.compareModParams(modA, modB))
    end)
    it("returns false when types differ", function()
        local modA = modLib.createMod("Life", "BASE", 50)
        local modB = modLib.createMod("Life", "INC", 50)
        assert.is_false(modLib.compareModParams(modA, modB))
    end)
end)
