-- test/unit/test_pob2_launch.lua
require("test_helpers")
local pob2 = require("pob2_testable")

-- validatePath
describe("validatePath", function()
    it("accepts a simple relative path", function()
        assert.is_true(pob2.validatePath("data/config.xml"))
    end)
    it("accepts an absolute path", function()
        assert.is_true(pob2.validatePath("/Users/user/Documents/build.xml"))
    end)
    it("accepts path with dots in filename", function()
        assert.is_true(pob2.validatePath("file.backup.txt"))
    end)
    it("rejects nil", function()
        assert.is_false(pob2.validatePath(nil))
    end)
    it("rejects number", function()
        assert.is_false(pob2.validatePath(42))
    end)
    it("rejects null byte injection", function()
        assert.is_false(pob2.validatePath("file.txt\0.exe"))
    end)
    it("rejects ../ traversal", function()
        assert.is_false(pob2.validatePath("../../../etc/passwd"))
    end)
    it("rejects ..\\ traversal", function()
        assert.is_false(pob2.validatePath("..\\..\\secret"))
    end)
    it("rejects semicolons", function()
        assert.is_false(pob2.validatePath("file; rm -rf /"))
    end)
    it("rejects pipe", function()
        assert.is_false(pob2.validatePath("file | cat /etc/passwd"))
    end)
    it("rejects backticks", function()
        assert.is_false(pob2.validatePath("`whoami`"))
    end)
    it("rejects dollar sign", function()
        assert.is_false(pob2.validatePath("$HOME/secret"))
    end)
    it("accepts empty string", function()
        assert.is_true(pob2.validatePath(""))
    end)
    it("accepts path with Japanese characters", function()
        assert.is_true(pob2.validatePath("data/ビルド/config.xml"))
    end)
end)

-- normalizeTextArg
describe("normalizeTextArg", function()
    it("returns empty string for nil", function()
        assert.are.equal("", pob2.normalizeTextArg(nil))
    end)
    it("returns string as-is", function()
        assert.are.equal("hello", pob2.normalizeTextArg("hello"))
    end)
    it("converts number to string", function()
        assert.are.equal("42", pob2.normalizeTextArg(42))
    end)
    it("converts boolean to string", function()
        assert.are.equal("true", pob2.normalizeTextArg(true))
    end)
    it("handles empty string", function()
        assert.are.equal("", pob2.normalizeTextArg(""))
    end)
end)

-- stripEscapes
describe("stripEscapes", function()
    it("removes numeric color codes", function()
        assert.are.equal("hello world", pob2.stripEscapes("^7hello ^1world"))
    end)
    it("removes hex color codes", function()
        assert.are.equal("test", pob2.stripEscapes("^xFFAABBtest"))
    end)
    it("returns unchanged string without escapes", function()
        assert.are.equal("plain text", pob2.stripEscapes("plain text"))
    end)
    it("handles empty string", function()
        assert.are.equal("", pob2.stripEscapes(""))
    end)
end)

-- shellQuote
describe("shellQuote", function()
    it("quotes a simple path", function()
        assert.are.equal("'hello'", pob2.shellQuote("hello"))
    end)
    it("escapes single quotes", function()
        assert.are.equal("'it'\\''s'", pob2.shellQuote("it's"))
    end)
    it("handles nil", function()
        assert.are.equal("''", pob2.shellQuote(nil))
    end)
end)

-- parseColorArg
describe("parseColorArg", function()
    it("parses hex color ^xRRGGBB", function()
        local r, g, b = pob2.parseColorArg("^xFF0000")
        assert.is_not_nil(r)
        assert.are.near(1.0, r, 0.01)
        assert.are.near(0.0, g, 0.01)
    end)
    it("parses ^7 as white", function()
        local r, g, b = pob2.parseColorArg("^7")
        assert.are.equal(1.0, r)
        assert.are.equal(1.0, g)
        assert.are.equal(1.0, b)
    end)
    it("returns nil for non-string", function()
        assert.is_nil(pob2.parseColorArg(42))
    end)
    it("produces Metal-safe values in [0,1]", function()
        local r, g, b = pob2.parseColorArg("^x808080")
        assert.is_true(r >= 0.0 and r <= 1.0)
        assert.is_true(g >= 0.0 and g <= 1.0)
        assert.is_true(b >= 0.0 and b <= 1.0)
    end)
end)

-- parsePattern
describe("parsePattern", function()
    it("extracts directory and file pattern", function()
        local dir, pat = pob2.parsePattern("/path/to/dir/*.xml")
        assert.are.equal("/path/to/dir", dir)
    end)
    it("uses current dir for bare pattern", function()
        local dir, pat = pob2.parsePattern("*.lua")
        assert.are.equal(".", dir)
    end)
end)

-- validateURL
describe("validateURL", function()
    it("accepts https URL", function()
        assert.is_not_nil(pob2.validateURL("https://example.com"))
    end)
    it("accepts http URL", function()
        assert.is_not_nil(pob2.validateURL("http://example.com"))
    end)
    it("rejects nil", function()
        assert.is_nil(pob2.validateURL(nil))
    end)
    it("rejects file:// protocol", function()
        assert.is_nil(pob2.validateURL("file:///etc/passwd"))
    end)
    it("rejects empty string", function()
        assert.is_nil(pob2.validateURL(""))
    end)
    it("escapes single quotes", function()
        local url = pob2.validateURL("https://example.com/path'injection")
        assert.is_not_nil(url)
        assert.is_nil(url:find("'"))
    end)
    it("rejects URLs with null bytes", function()
        assert.is_nil(pob2.validateURL("https://example.com\0evil"))
    end)
end)
